---
- name: AUTOMATIC BACKUP OF RUNNING-CONFIG
  hosts: CSR1kv
  gather_facts: false
  connection: local
#kern - geen linux facts gebruiken, router is geen linux

  tasks:
    - name: DISPLAYING THE RUNNING-CONFIG
      ios_command:
        commands:
          - show running-config
        timeout: 60
      register: config

    - name: SAVE OUTPUT TO ./backups/
      copy:
        content: "{{ config.stdout[0] }}" #bevat de ruwe uitvoer van de commando met eerste element uit de lijst
        dest: "backups/show_run_{{ inventory_hostname }}.txt" #--> schrijft letterlijk de output naar hier
